### ISSUE TITLE
[Bug] rocketact-script@1.6.2 start & build error 

### ISSUE THREAD

**Issue by beanlee** [jdf2e/rocketact#23]
**Describe the bug**

```bash
 $ yarn start
yarn run v1.13.0
$ rocketact-scripts start
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/config/webpack/module.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**Environment (please complete the following information):**
 - Version: rocketact-script@1.6.2 rocketact-plugin-polyfill@0.1.5

**Comment by beanlee** [comment]
update after add `autoprefixer` & `postcss-flexbugs-fixes`

```bash
yarn run v1.13.0
$ rocketact-scripts start
(node:63970) UnhandledPromiseRejectionWarning: TypeError: options.plugins is not iterable
    at webpackChain.module.rule.use.tap.options (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-plugin-polyfill/index.js:13:24)
    at Object.tap (/Users/lilong3/work/code/pc/xxx/node_modules/webpack-chain/src/Use.js:14:20)
    at api.chainWebpack.webpackChain (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-plugin-polyfill/index.js:9:8)
    at webpackChainFns.forEach.fn (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/Core.js:20:44)
    at Array.forEach (<anonymous>)
    at Core.applyWebpackChainFns (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/Core.js:20:30)
    at Core.resolveWebpackConfig (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/Core.js:46:18)
    at CoreAPI.resolveWebpackConfig (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/CoreAPI.js:14:26)
    at Promise (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/commands/start.js:18:39)
    at new Promise (<anonymous>)
    at Object.api.registerCommand [as fn] (/Users/xxx/work/code/pc/xxx/node_modules/rocketact-scripts/dist/commands/start.js:17:16)
    at Core.run (/Users/lilong3/work/code/pc/xxx/node_modules/rocketact-scripts/dist/Core.js:59:39)
    at Object.<anonymous> (/Users/lilong3/work/code/pc/xxx/node_modules/rocketact-scripts/dist/bin/rocketact-scripts.js:29:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
(node:63970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63970) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
